import { Gabriela, Poppins } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../../Providers/ThemeProvider";
import { Toaster } from "react-hot-toast";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});
export const metadata = {
  title: "Hi Study Next js App",
  description: "Generated by create next app",
};
const gabriela = Gabriela({
  variable: "--font-gabriela",
  subsets: ["latin"],
  weight: "400",
});
export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.variable} ${gabriela.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <Toaster position="top-center" reverseOrder={false} />
        </ThemeProvider>
      </body>
    </html>
  );
}
